### ISSUE TITLE
[Bug]: Create button not working

### ISSUE THREAD

**Issue by KendallDoesCoding** [ProtonDesigner/core#10]
### What happened?

I was trying to create a project and tapped the "Create" button but nothing is working/the project isn't getting created.

### Version

v0.2.2

### Duplicate Issues

- [X] There are no duplicate issues/the solutions provided don't work for me.

**Comment by TechStudent10** [comment]
Did you try pressing Control + R when you created it?

**Comment by KendallDoesCoding** [comment]
> Did you try pressing Control + R when you created it?

No. Do i have to?

**Comment by TechStudent10** [comment]
> > Did you try pressing Control + R when you created it?
> 
> No. Do i have to?
> 

For now, yes.

**Comment by KendallDoesCoding** [comment]
> > > Did you try pressing Control + R when you created it?
> > 
> > 
> > No. Do i have to?
> 
> For now, yes.

Ok, let me see.

**Comment by KendallDoesCoding** [comment]
The project that I created before got created just becoz of a glitch it didn't show up!

**Comment by TechStudent10** [comment]
Reopening until fixed.
