### ISSUE TITLE
[Bug]: Issues when signing up.

### ISSUE THREAD

**Issue by KendallDoesCoding** [ProtonDesigner/core#12]
### What happened?

When creating a account when you tap "Signup" the first time you get a issue, when you tap it the second time as well you get a issue...

It works the third time and your account gets created, although sometimes it sticks with the second time error - Failed to create record, and doesn't create the account at all.

**FIRST TIME**:
![image](https://user-images.githubusercontent.com/84712013/221104326-7af4bb7d-7e67-4c86-bb7b-3802e17cf3a0.png)

**SECOND TIME**:
![image](https://user-images.githubusercontent.com/84712013/221104158-823cc420-e3ca-4717-aae6-617fa6c1c729.png)

### Version

v0.2.2

### Duplicate Issues

- [X] There are no duplicate issues/the solutions provided don't work for me.

**Comment by TechStudent10** [comment]
You are literally trying to make an account called test.

**Comment by KendallDoesCoding** [comment]
> You are literally trying to make an account called test.

Same issue came when I made a real account?

**Comment by KendallDoesCoding** [comment]
also why should the issue come if the account is called test??

**Comment by TechStudent10** [comment]
> also why should the issue come if the account is called test??
> 

Because it already exists. It's used internally I think

**Comment by TechStudent10** [comment]
> > You are literally trying to make an account called test.
> 
> Same issue came when I made a real account?

Username is too short. I need to make more descriptive errors.

**Comment by KendallDoesCoding** [comment]
> > also why should the issue come if the account is called test??
> 
> Because it already exists. It's used internally I think

Ok, but when I created a account called "Ken" I faced the same issue. First click I got the first issue, second time I got the second issue then I tapped again and the acc created.

**Comment by KendallDoesCoding** [comment]
> > > You are literally trying to make an account called test.
> > 
> > 
> > Same issue came when I made a real account?
> 
> Username is too short. I need to make more descriptive errors.

Yes, please. Or make it so that users can't create usernames under certain characters.

**Comment by TechStudent10** [comment]
> > > > You are literally trying to make an account called test.
> > > 
> > > 
> > > Same issue came when I made a real account?
> > 
> > Username is too short. I need to make more descriptive errors.
> 
> Yes, please. Or make it so that users can't create usernames under certain characters.
> 

They can't. My db won't allow it

**Comment by KendallDoesCoding** [comment]
> > > > > You are literally trying to make an account called test.
> > > > 
> > > > 
> > > > Same issue came when I made a real account?
> > > 
> > > 
> > > Username is too short. I need to make more descriptive errors.
> > 
> > 
> > Yes, please. Or make it so that users can't create usernames under certain characters.
> 
> They can't. My db won't allow it

Oh okay, no worries.

**Comment by TechStudent10** [comment]
Reopening until fixed...
