### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by KendallDoesCoding** [ProtonDesigner/core#8]
Hey,

I need some support on how I can run this on my computer. What must I install, etc?

**Comment by TechStudent10** [comment]
Releases tab

**Comment by KendallDoesCoding** [comment]
> Releases tab

I should download everything?

**Comment by TechStudent10** [comment]
> > Releases tab
> 
> I should download everything?

No. Based on your platform, you should be able to determine what file you need to download. `.msi` for Windows, `.dmg` for Mac and `.deb` and `.AppImage` for Linux.

**Comment by KendallDoesCoding** [comment]
> > > Releases tab
> > 
> > 
> > I should download everything?
> 
> No. Based on your platform, you should be able to determine what file you need to download. `.msi` for Windows, `.app.zip` for Mac and `.deb` and `.AppImage` for Linux.

Ok, thanks a ton!
